Main view
arleta-jedrzejczak/cc-react-project pull request #6
Opened 2021-04-12 18:15 UTC by T40N

Pull request for first view on my work with displaying the posts. Dont merge jet .

2021-04-13 14:46 UTC, arleta-jedrzejczak approved these changes

2021-04-13 14:46 UTC, arleta-jedrzejczak commented on src/components/main/postGrid.tsx
> +    kupka: {
???

2021-04-14 14:12 UTC, arleta-jedrzejczak requested changes

2021-04-14 14:12 UTC, arleta-jedrzejczak commented on src/components/main.tsx
> +      // vertical padding + font size from searchIcon
to delete

2021-04-14 14:12 UTC, arleta-jedrzejczak commented on src/components/main.tsx
> +  createStyles({
move styles to separate file

2021-04-14 14:12 UTC, arleta-jedrzejczak commented on src/components/main/isLogedMenu.tsx
> +
leave 1 row

2021-04-14 14:12 UTC, arleta-jedrzejczak commented on src/components/main/isLogedMenu.tsx
> +    console.log(typeof(sessionStorage.getItem('id')));
to delete

2021-04-14 14:12 UTC, arleta-jedrzejczak commented on src/components/main/isLogedMenu.tsx
> +    console.log(typeof(sessionStorage.getItem('id')));
use Prettier

2021-04-14 14:12 UTC, arleta-jedrzejczak commented on src/components/main/postGrid.tsx
> +const useStyles = makeStyles({
move to separate file

2021-04-14 14:12 UTC, arleta-jedrzejczak commented on src/components/user/user.tsx
> +  console.log(posts);
to delete

2021-04-14 14:12 UTC, arleta-jedrzejczak commented on src/components/user/user.tsx
> +      .get(`https://damp-ridge-27698.herokuapp.com/users/606a0e06d2dade415814a66d`)
it should be hardcoded?

2021-04-14 14:45 UTC, T40N commented on src/components/main.tsx
> +  createStyles({
Done!

2021-04-14 14:45 UTC, T40N commented on src/components/main/isLogedMenu.tsx
> +
Done!

2021-04-14 14:45 UTC, T40N commented on src/components/main/isLogedMenu.tsx
> +    console.log(typeof(sessionStorage.getItem('id')));
Done!

2021-04-14 14:45 UTC, T40N commented on src/components/main/postGrid.tsx
> +const useStyles = makeStyles({
Done!

2021-04-14 14:53 UTC, T40N commented on src/components/user/user.tsx
> +      .get(`https://damp-ridge-27698.herokuapp.com/users/606a0e06d2dade415814a66d`)
Done!

2021-04-14 14:54 UTC, T40N commented on src/components/main.tsx
> +      // vertical padding + font size from searchIcon
Done!

2021-04-14 14:56 UTC, arleta-jedrzejczak approved these changes

2021-04-14 14:57 UTC, merged